"""Type definitions and Protocols for Bosch integration."""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable
from datetime import datetime

@runtime_checkable
class BoschObject(Protocol):
    """Protocol for Bosch library objects."""

    @property
    def name(self) -> str:
        """Return name of the object."""
        ...

    @property
    def id(self) -> str:
        """Return ID of the object."""
        ...

    @property
    def attr_id(self) -> str:
        """Return Attribute ID of the object."""
        ...

    @property
    def parent_id(self) -> str | None:
        """Return parent ID of the object."""
        ...

    @property
    def path(self) -> str:
        """Return path of the object."""
        ...

    @property
    def state(self) -> Any:
        """Return state of the object."""
        ...

    @property
    def state_message(self) -> str:
        """Return state message of the object."""
        ...

    @property
    def update_initialized(self) -> bool:
        """Return if update is initialized."""
        ...

    @property
    def last_entry(self) -> Any:
        """Return last entry of the object."""
        ...

    async def update(self, _time: datetime | None = None) -> None:
        """Update the object."""
        ...

    def get_property(self, path: str) -> dict[str, Any] | None:
        """Get property from the object."""
        ...

    @property
    def min_temp(self) -> float | None:
        """Return minimum temperature."""
        ...

    @property
    def max_temp(self) -> float | None:
        """Return maximum temperature."""
        ...

    @property
    def device_class(self) -> str | None: ...
    @property
    def state_class(self) -> str | None: ...
    @property
    def entity_category(self) -> str | None: ...

    async def fetch_range(self, start_time: datetime, stop_time: datetime) -> list[Any]: ...
    async def fetch_all(self) -> dict[Any, Any]: ...

@runtime_checkable
class BoschGateway(Protocol):
    """Protocol for Bosch library gateway."""

    @property
    def device_model(self) -> str | None: ...
    @property
    def device_type(self) -> str | None: ...
    @property
    def device_name(self) -> str | None: ...
    @property
    def firmware(self) -> str | None: ...
    @property
    def uuid(self) -> str | None: ...
    @property
    def bus_type(self) -> str | None: ...
    @property
    def database(self) -> dict[str, Any] | None: ...

    async def check_connection(self) -> None: ...
    async def get_capabilities(self) -> list[str]: ...
    async def custom_initialize(self, database: dict[str, Any]) -> None: ...
    
    async def raw_put(self, path: str, value: Any) -> None: ...
    async def raw_query(self, path: str) -> Any: ...
    async def rawscan(self) -> dict[str, Any]: ...
    async def close(self) -> None: ...

    async def __aenter__(self) -> BoschGateway: ...
    async def __aexit__(self, _exc_type: Any, _exc_val: Any, _exc_tb: Any) -> None: ...

    # Collections as exposed by bosch_thermostat_client.gateway.base.BaseGateway.
    # ``sensors`` also contains recording/energy sensors (see ``BoschObject.kind``).
    @property
    def sensors(self) -> list[BoschObject]: ...
    @property
    def heating_circuits(self) -> list[BoschObject]: ...
    @property
    def dhw_circuits(self) -> list[BoschObject]: ...
    @property
    def solar_circuits(self) -> list[BoschObject]: ...
    def get_circuits(self, ctype: str) -> list[Any]: ...
    @property
    def regular_switches(self) -> list[BoschObject]: ...
    @property
    def number_switches(self) -> list[BoschObject]: ...
    @property
    def select_switches(self) -> list[BoschObject] | None: ...
